[versions]
# libraries
assertj = "3.27.6"
# testing
mockk = "1.14.7"
junit = "6.0.2"
# plugins
kotlin = "2.3.0"
detekt = "1.23.8"
dokka = "2.1.0"
publish-plugin = "2.0.0"
kover = "0.9.4"
test-retry = "1.6.4"

[libraries]
assertj-bom = { module = "org.assertj:assertj-bom", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
test-retry = { id = "org.gradle.test-retry", version.ref = "test-retry" }

